import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(21, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(23, GPIO.OUT)
GPIO.setup(24, GPIO.OUT)
GPIO.setup(25, GPIO.OUT)

GPIO.output(18, False)
GPIO.output(17, False)
GPIO.output(21, False)
GPIO.output(22, False)
GPIO.output(23, False)
GPIO.output(24, False)
GPIO.output(25, False)
time.sleep(2)

GPIO.output(18, True)
time.sleep(1)
GPIO.output(17, True)
time.sleep(1)
GPIO.output(21, True)
time.sleep(1)
GPIO.output(22, True)
time.sleep(1)
GPIO.output(23, True)
time.sleep(1)
GPIO.output(24, True)
time.sleep(1)
GPIO.output(25, True)
time.sleep(1)

GPIO.output(18, False)
GPIO.output(17, False)
GPIO.output(21, False)
GPIO.output(22, False)
GPIO.output(23, False)
GPIO.output(24, False)
GPIO.output(25, False)
